### ISSUE TITLE
Data structure with no events not supported

### ISSUE THREAD

**Issue by laurivaltteri** [bwrc/neurone-r#3]
neurone:::read_events(testdir)
Error in `[<-`(`*tmp*`, i, , value = c(0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L,  :  subscript out of bounds

add:

> read_events <- function (datadir, session.number = 1, samplingrate = NULL) {
>      files.events <- neurone:::get_event_files(datadir, session.number = session.number)
>      f <- file(files.events[["events"]], "rb")
>      f.info <- file.info(files.events[["events"]])
>      n.events <- f.info$size/88
>      events <- matrix(nrow = n.events, ncol = 16)
>      **_if (!length(events)) close(f);return(0)_**
>      event.structure <- get_event_structure() ....

and:

> assignInNamespace("read_events",read_events,"neurone")

**Comment by aheneliu** [comment]
Fixed.
